<a href="https://colab.research.google.com/github/Capedcrusaders/math-statistics/blob/main/linear%20algebra/linear_algebra_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#declaring a vector in python using a list

vector = [3,2]
print(vector)

#declaring a vector in python using numpy
import numpy as np
vector1 =np.array([3,2])
print(vector1)

#declaring a five dimension vector
import numpy as np
vector2 = np.array([1,2,3,4,5])
print(vector2)

[3, 2]
[3 2]
[1 2 3 4 5]


In [ ]:
#Adding two vector using numpy
from numpy import array
v = array([3,2])
w = array([2,-1])

# Sum the vectors
v_plus_w = v+w
print(v_plus_w) #[5,1]


[5 1]


In [ ]:
# Scaling a number in python using numpy

from numpy import array
vec = array([3,1])

#scale the vector
scaled_vec = 2 * vec
print(scaled_vec) #[6,2]

[6 2]


In [ ]:
# MATRIX VECTOR MULTIPICATION IN NUMPY

from numpy import array
#compose basis matrix with 1-hat and j-hat
basis = array(
    [[3,0],
     [0,2]]
)
#declare vector m
m= array([1,1])
#create a new vector
#by transformng v with dot product
new_m = basis.dot(m)
print(new_m) #[3,2]

[3 2]


In [ ]:
# seprating basis vector and applying them as a transformation & traansforming a vector using numpy

from numpy import array
#declare i-hat and j-hat
i_hat = array([2,0])
j_hat = array([0,3])
#compose basis matrix with 1-hat and j-hat
#also need to transpose rows into columns
basis =array([i_hat,j_hat]).transpose() #Fixed typo here

#declare vector m
m= array([1,1])
#create a new vector
#by transformng v with dot product
new_m = basis.dot(m)
print(new_m) #[3,2]

[2 3]


In [ ]:
# COMBINING TWO TRANSFORMATIONS OR REVERSE OF TRANSFORMATIONS
from numpy import array
#transportaion 1
i_hat1 = array([0,1])
j_hat1 = array([-1,0])
transform1=array([i_hat1,j_hat1]).transpose()

#transportaion 2
i_hat2 = array([1,0])
j_hat2 = array([0,1])
transform2=array([i_hat2,j_hat2]).transpose()

# combine transformtions
combined =transform1 @ transform2
#test
print("combined matrix:\n {}".format(combined))

v=array([1,2])
print(combined.dot(v))

combined matrix:
 [[ 0 -1]
 [ 1  0]]
[-2  1]


In [1]:
# CALCULATING A DETERMINANT  OR DETERMINAT FOR A SHEAR
""" Determinat describes how much a sample area in vector space changes in scale with linear transformation"""

from numpy.linalg import det
from numpy import array

i_hat = array([3,0])
j_hat = array([0,2])

dete = array([i_hat,j_hat]).transpose()
determinat = det(dete)
print(determinat)


6.0


In [2]:
# A DETEMINANT ON A FLIPPED SPACE IS NEGATIVE
# A NEGATIVE DETERMINAT

from numpy.linalg import det
from numpy import array

i_hat = array([-2,1])
j_hat = array([1,2])

deter = array([i_hat,j_hat]).transpose()
determinats = det(deter)
print(determinats)

-5.000000000000001


In [3]:
""" if you have a determinat 0,thats means all of the spaces has been squished into a lesser dimension."""
#A DETERMINANT OF LINAER DEPENDANCE IN 2D AND 3D

from numpy.linalg import det
from numpy import array
i_hat = array([-2,1])
j_hat = array([3,-1.5])

bass = array([i_hat,j_hat]).transpose()
determinat1 = det(bass)
print(determinat1)

0.0


form there we solve the system equation using sumpy and numpy


In [5]:
# using sumpy to study the inverse and identity matrix
from sympy import Matrix

#4x+2y+4z=44
#5x+3y+7z=56
#9x+3y+6z=72

a=Matrix([
    [4,2,4],
    [5,3,7],
    [9,3,6]
])
#dot product between a and its reverse
# will produce identity function
inverse =a.inv()
identity = inverse*a
# now print
print("inverse: {}".format(inverse))
print("identity: {}".format(identity))

inverse: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
identity: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [6]:
# USING SUMPY TO SOLVE SYSTEM OF EQUATION
from numpy import array
from numpy.linalg import inv

A = array([
    [4,2,4],
    [5,3,7],
    [9,3,6]
])

B= array([
    44,
    56,
    72
])
X=inv(A).dot(B)
print(X)

[ 2. 34. -8.]


In [7]:
#using sympy to solve system of equation
from sympy import Matrix
from sympy.abc import x,y,z

a=Matrix([
    [4,2,4],
    [5,3,7],
    [9,3,6]
])
b=Matrix([44,56,72])
x=a.inv()*b
print(x)


Matrix([[2], [34], [-8]])


**eigenvalves and eigenvectors**

Eigenvalues are the special set of scalar values that is associated with the set of linear equations most probably in the matrix equations. The eigenvectors are also termed as characteristic roots. It is a non-zero vector that can be changed at most by its scalar factor after the application of linear transformations.




In [8]:
# performing eigendecomposition in numpy
from numpy import array,diag
from numpy.linalg import eig ,inv

A = array([
    [1,2],
    [4,5],
])
eigenvals,eigenvecs = eig(A)
print('EIGENVALUES')
print(eigenvals)
print('\nEIGENVector')
print(eigenvecs)

EIGENVALUES
[-0.46410162  6.46410162]

EIGENVector
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [9]:
#decomposing and recomposing a matrix in numpy
from numpy import array,diag
from numpy.linalg import eig ,inv

A = array([
    [1,2],
    [4,5],
])
eigenvals,eigenvecs = eig(A)
print('EIGENVALUES')
print(eigenvals)
print('\nEIGENVector')
print(eigenvecs)

print("\nREBUILD MATRIX")
Q=eigenvecs
R=inv(Q)

L=diag(eigenvals)
B=Q @ L @ R
print(B)


EIGENVALUES
[-0.46410162  6.46410162]

EIGENVector
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

REBUILD MATRIX
[[1. 2.]
 [4. 5.]]
